// Kuzu Database Schema - test_db
// 20 Node Tables, 17 Edge Tables
// Auto-generated from data/test_db

// ---- Node Tables ----
CREATE NODE TABLE GroupItem (id INT64, name STRING, email STRING, phone STRING, address STRING, city STRING, country STRING, zipcode STRING, bio STRING, status STRING, role STRING, tier STRING, level STRING, badge STRING, category STRING, tag STRING, label STRING, score DOUBLE, rating DOUBLE, balance DOUBLE, income DOUBLE, price DOUBLE, discount DOUBLE, tax DOUBLE, weight DOUBLE, age INT64, count INT64, views INT64, likes INT64, shares INT64, followers INT64, friends INT64, posts INT64, flag_a BOOL, flag_b BOOL, flag_c BOOL, flag_d BOOL, flag_e BOOL, flag_f BOOL, flag_g BOOL, flag_h BOOL, flag_i BOOL, metric_a DOUBLE, metric_b DOUBLE, metric_c DOUBLE, metric_d DOUBLE, desc_a STRING, desc_b STRING, desc_c STRING, desc_d STRING, created_at STRING, updated_at STRING, deleted_at STRING, published_at STRING, extra_a STRING, extra_b STRING, extra_c STRING, extra_d STRING, value_a DOUBLE, value_b DOUBLE, PRIMARY KEY (id));

CREATE NODE TABLE CommentItem (id INT64, name STRING, email STRING, phone STRING, address STRING, city STRING, country STRING, zipcode STRING, bio STRING, status STRING, role STRING, tier STRING, level STRING, badge STRING, category STRING, tag STRING, label STRING, score DOUBLE, rating DOUBLE, balance DOUBLE, income DOUBLE, price DOUBLE, discount DOUBLE, tax DOUBLE, weight DOUBLE, age INT64, count INT64, views INT64, likes INT64, shares INT64, followers INT64, friends INT64, posts INT64, flag_a BOOL, flag_b BOOL, flag_c BOOL, flag_d BOOL, flag_e BOOL, flag_f BOOL, flag_g BOOL, flag_h BOOL, flag_i BOOL, metric_a DOUBLE, metric_b DOUBLE, metric_c DOUBLE, metric_d DOUBLE, desc_a STRING, desc_b STRING, desc_c STRING, desc_d STRING, created_at STRING, updated_at STRING, deleted_at STRING, published_at STRING, extra_a STRING, extra_b STRING, extra_c STRING, extra_d STRING, value_a DOUBLE, value_b DOUBLE, PRIMARY KEY (id));

CREATE NODE TABLE TaskItem (id INT64, name STRING, email STRING, phone STRING, address STRING, city STRING, country STRING, zipcode STRING, bio STRING, status STRING, role STRING, tier STRING, level STRING, badge STRING, category STRING, tag STRING, label STRING, score DOUBLE, rating DOUBLE, balance DOUBLE, income DOUBLE, price DOUBLE, discount DOUBLE, tax DOUBLE, weight DOUBLE, age INT64, count INT64, views INT64, likes INT64, shares INT64, followers INT64, friends INT64, posts INT64, flag_a BOOL, flag_b BOOL, flag_c BOOL, flag_d BOOL, flag_e BOOL, flag_f BOOL, flag_g BOOL, flag_h BOOL, flag_i BOOL, metric_a DOUBLE, metric_b DOUBLE, metric_c DOUBLE, metric_d DOUBLE, desc_a STRING, desc_b STRING, desc_c STRING, desc_d STRING, created_at STRING, updated_at STRING, deleted_at STRING, published_at STRING, extra_a STRING, extra_b STRING, extra_c STRING, extra_d STRING, value_a DOUBLE, value_b DOUBLE, PRIMARY KEY (id));

CREATE NODE TABLE Account (id INT64, name STRING, email STRING, phone STRING, address STRING, city STRING, country STRING, zipcode STRING, bio STRING, status STRING, role STRING, tier STRING, level STRING, badge STRING, category STRING, tag STRING, label STRING, score DOUBLE, rating DOUBLE, balance DOUBLE, income DOUBLE, price DOUBLE, discount DOUBLE, tax DOUBLE, weight DOUBLE, age INT64, count INT64, views INT64, likes INT64, shares INT64, followers INT64, friends INT64, posts INT64, flag_a BOOL, flag_b BOOL, flag_c BOOL, flag_d BOOL, flag_e BOOL, flag_f BOOL, flag_g BOOL, flag_h BOOL, flag_i BOOL, metric_a DOUBLE, metric_b DOUBLE, metric_c DOUBLE, metric_d DOUBLE, desc_a STRING, desc_b STRING, desc_c STRING, desc_d STRING, created_at STRING, updated_at STRING, deleted_at STRING, published_at STRING, extra_a STRING, extra_b STRING, extra_c STRING, extra_d STRING, value_a DOUBLE, value_b DOUBLE, PRIMARY KEY (id));

CREATE NODE TABLE Tag (id INT64, name STRING, email STRING, phone STRING, address STRING, city STRING, country STRING, zipcode STRING, bio STRING, status STRING, role STRING, tier STRING, level STRING, badge STRING, category STRING, tag STRING, label STRING, score DOUBLE, rating DOUBLE, balance DOUBLE, income DOUBLE, price DOUBLE, discount DOUBLE, tax DOUBLE, weight DOUBLE, age INT64, count INT64, views INT64, likes INT64, shares INT64, followers INT64, friends INT64, posts INT64, flag_a BOOL, flag_b BOOL, flag_c BOOL, flag_d BOOL, flag_e BOOL, flag_f BOOL, flag_g BOOL, flag_h BOOL, flag_i BOOL, metric_a DOUBLE, metric_b DOUBLE, metric_c DOUBLE, metric_d DOUBLE, desc_a STRING, desc_b STRING, desc_c STRING, desc_d STRING, created_at STRING, updated_at STRING, deleted_at STRING, published_at STRING, extra_a STRING, extra_b STRING, extra_c STRING, extra_d STRING, value_a DOUBLE, value_b DOUBLE, PRIMARY KEY (id));

CREATE NODE TABLE Category (id INT64, name STRING, email STRING, phone STRING, address STRING, city STRING, country STRING, zipcode STRING, bio STRING, status STRING, role STRING, tier STRING, level STRING, badge STRING, category STRING, tag STRING, label STRING, score DOUBLE, rating DOUBLE, balance DOUBLE, income DOUBLE, price DOUBLE, discount DOUBLE, tax DOUBLE, weight DOUBLE, age INT64, count INT64, views INT64, likes INT64, shares INT64, followers INT64, friends INT64, posts INT64, flag_a BOOL, flag_b BOOL, flag_c BOOL, flag_d BOOL, flag_e BOOL, flag_f BOOL, flag_g BOOL, flag_h BOOL, flag_i BOOL, metric_a DOUBLE, metric_b DOUBLE, metric_c DOUBLE, metric_d DOUBLE, desc_a STRING, desc_b STRING, desc_c STRING, desc_d STRING, created_at STRING, updated_at STRING, deleted_at STRING, published_at STRING, extra_a STRING, extra_b STRING, extra_c STRING, extra_d STRING, value_a DOUBLE, value_b DOUBLE, PRIMARY KEY (id));

CREATE NODE TABLE Product (id INT64, name STRING, email STRING, phone STRING, address STRING, city STRING, country STRING, zipcode STRING, bio STRING, status STRING, role STRING, tier STRING, level STRING, badge STRING, category STRING, tag STRING, label STRING, score DOUBLE, rating DOUBLE, balance DOUBLE, income DOUBLE, price DOUBLE, discount DOUBLE, tax DOUBLE, weight DOUBLE, age INT64, count INT64, views INT64, likes INT64, shares INT64, followers INT64, friends INT64, posts INT64, flag_a BOOL, flag_b BOOL, flag_c BOOL, flag_d BOOL, flag_e BOOL, flag_f BOOL, flag_g BOOL, flag_h BOOL, flag_i BOOL, metric_a DOUBLE, metric_b DOUBLE, metric_c DOUBLE, metric_d DOUBLE, desc_a STRING, desc_b STRING, desc_c STRING, desc_d STRING, created_at STRING, updated_at STRING, deleted_at STRING, published_at STRING, extra_a STRING, extra_b STRING, extra_c STRING, extra_d STRING, value_a DOUBLE, value_b DOUBLE, PRIMARY KEY (id));

CREATE NODE TABLE VideoItem (id INT64, name STRING, email STRING, phone STRING, address STRING, city STRING, country STRING, zipcode STRING, bio STRING, status STRING, role STRING, tier STRING, level STRING, badge STRING, category STRING, tag STRING, label STRING, score DOUBLE, rating DOUBLE, balance DOUBLE, income DOUBLE, price DOUBLE, discount DOUBLE, tax DOUBLE, weight DOUBLE, age INT64, count INT64, views INT64, likes INT64, shares INT64, followers INT64, friends INT64, posts INT64, flag_a BOOL, flag_b BOOL, flag_c BOOL, flag_d BOOL, flag_e BOOL, flag_f BOOL, flag_g BOOL, flag_h BOOL, flag_i BOOL, metric_a DOUBLE, metric_b DOUBLE, metric_c DOUBLE, metric_d DOUBLE, desc_a STRING, desc_b STRING, desc_c STRING, desc_d STRING, created_at STRING, updated_at STRING, deleted_at STRING, published_at STRING, extra_a STRING, extra_b STRING, extra_c STRING, extra_d STRING, value_a DOUBLE, value_b DOUBLE, PRIMARY KEY (id));

CREATE NODE TABLE OrderItem (id INT64, name STRING, email STRING, phone STRING, address STRING, city STRING, country STRING, zipcode STRING, bio STRING, status STRING, role STRING, tier STRING, level STRING, badge STRING, category STRING, tag STRING, label STRING, score DOUBLE, rating DOUBLE, balance DOUBLE, income DOUBLE, price DOUBLE, discount DOUBLE, tax DOUBLE, weight DOUBLE, age INT64, count INT64, views INT64, likes INT64, shares INT64, followers INT64, friends INT64, posts INT64, flag_a BOOL, flag_b BOOL, flag_c BOOL, flag_d BOOL, flag_e BOOL, flag_f BOOL, flag_g BOOL, flag_h BOOL, flag_i BOOL, metric_a DOUBLE, metric_b DOUBLE, metric_c DOUBLE, metric_d DOUBLE, desc_a STRING, desc_b STRING, desc_c STRING, desc_d STRING, created_at STRING, updated_at STRING, deleted_at STRING, published_at STRING, extra_a STRING, extra_b STRING, extra_c STRING, extra_d STRING, value_a DOUBLE, value_b DOUBLE, PRIMARY KEY (id));

CREATE NODE TABLE PostItem (id INT64, name STRING, email STRING, phone STRING, address STRING, city STRING, country STRING, zipcode STRING, bio STRING, status STRING, role STRING, tier STRING, level STRING, badge STRING, category STRING, tag STRING, label STRING, score DOUBLE, rating DOUBLE, balance DOUBLE, income DOUBLE, price DOUBLE, discount DOUBLE, tax DOUBLE, weight DOUBLE, age INT64, count INT64, views INT64, likes INT64, shares INT64, followers INT64, friends INT64, posts INT64, flag_a BOOL, flag_b BOOL, flag_c BOOL, flag_d BOOL, flag_e BOOL, flag_f BOOL, flag_g BOOL, flag_h BOOL, flag_i BOOL, metric_a DOUBLE, metric_b DOUBLE, metric_c DOUBLE, metric_d DOUBLE, desc_a STRING, desc_b STRING, desc_c STRING, desc_d STRING, created_at STRING, updated_at STRING, deleted_at STRING, published_at STRING, extra_a STRING, extra_b STRING, extra_c STRING, extra_d STRING, value_a DOUBLE, value_b DOUBLE, PRIMARY KEY (id));

CREATE NODE TABLE EventItem (id INT64, name STRING, email STRING, phone STRING, address STRING, city STRING, country STRING, zipcode STRING, bio STRING, status STRING, role STRING, tier STRING, level STRING, badge STRING, category STRING, tag STRING, label STRING, score DOUBLE, rating DOUBLE, balance DOUBLE, income DOUBLE, price DOUBLE, discount DOUBLE, tax DOUBLE, weight DOUBLE, age INT64, count INT64, views INT64, likes INT64, shares INT64, followers INT64, friends INT64, posts INT64, flag_a BOOL, flag_b BOOL, flag_c BOOL, flag_d BOOL, flag_e BOOL, flag_f BOOL, flag_g BOOL, flag_h BOOL, flag_i BOOL, metric_a DOUBLE, metric_b DOUBLE, metric_c DOUBLE, metric_d DOUBLE, desc_a STRING, desc_b STRING, desc_c STRING, desc_d STRING, created_at STRING, updated_at STRING, deleted_at STRING, published_at STRING, extra_a STRING, extra_b STRING, extra_c STRING, extra_d STRING, value_a DOUBLE, value_b DOUBLE, PRIMARY KEY (id));

CREATE NODE TABLE LocationItem (id INT64, name STRING, email STRING, phone STRING, address STRING, city STRING, country STRING, zipcode STRING, bio STRING, status STRING, role STRING, tier STRING, level STRING, badge STRING, category STRING, tag STRING, label STRING, score DOUBLE, rating DOUBLE, balance DOUBLE, income DOUBLE, price DOUBLE, discount DOUBLE, tax DOUBLE, weight DOUBLE, age INT64, count INT64, views INT64, likes INT64, shares INT64, followers INT64, friends INT64, posts INT64, flag_a BOOL, flag_b BOOL, flag_c BOOL, flag_d BOOL, flag_e BOOL, flag_f BOOL, flag_g BOOL, flag_h BOOL, flag_i BOOL, metric_a DOUBLE, metric_b DOUBLE, metric_c DOUBLE, metric_d DOUBLE, desc_a STRING, desc_b STRING, desc_c STRING, desc_d STRING, created_at STRING, updated_at STRING, deleted_at STRING, published_at STRING, extra_a STRING, extra_b STRING, extra_c STRING, extra_d STRING, value_a DOUBLE, value_b DOUBLE, PRIMARY KEY (id));

CREATE NODE TABLE Company (id INT64, name STRING, email STRING, phone STRING, address STRING, city STRING, country STRING, zipcode STRING, bio STRING, status STRING, role STRING, tier STRING, level STRING, badge STRING, category STRING, tag STRING, label STRING, score DOUBLE, rating DOUBLE, balance DOUBLE, income DOUBLE, price DOUBLE, discount DOUBLE, tax DOUBLE, weight DOUBLE, age INT64, count INT64, views INT64, likes INT64, shares INT64, followers INT64, friends INT64, posts INT64, flag_a BOOL, flag_b BOOL, flag_c BOOL, flag_d BOOL, flag_e BOOL, flag_f BOOL, flag_g BOOL, flag_h BOOL, flag_i BOOL, metric_a DOUBLE, metric_b DOUBLE, metric_c DOUBLE, metric_d DOUBLE, desc_a STRING, desc_b STRING, desc_c STRING, desc_d STRING, created_at STRING, updated_at STRING, deleted_at STRING, published_at STRING, extra_a STRING, extra_b STRING, extra_c STRING, extra_d STRING, value_a DOUBLE, value_b DOUBLE, PRIMARY KEY (id));

CREATE NODE TABLE Department (id INT64, name STRING, email STRING, phone STRING, address STRING, city STRING, country STRING, zipcode STRING, bio STRING, status STRING, role STRING, tier STRING, level STRING, badge STRING, category STRING, tag STRING, label STRING, score DOUBLE, rating DOUBLE, balance DOUBLE, income DOUBLE, price DOUBLE, discount DOUBLE, tax DOUBLE, weight DOUBLE, age INT64, count INT64, views INT64, likes INT64, shares INT64, followers INT64, friends INT64, posts INT64, flag_a BOOL, flag_b BOOL, flag_c BOOL, flag_d BOOL, flag_e BOOL, flag_f BOOL, flag_g BOOL, flag_h BOOL, flag_i BOOL, metric_a DOUBLE, metric_b DOUBLE, metric_c DOUBLE, metric_d DOUBLE, desc_a STRING, desc_b STRING, desc_c STRING, desc_d STRING, created_at STRING, updated_at STRING, deleted_at STRING, published_at STRING, extra_a STRING, extra_b STRING, extra_c STRING, extra_d STRING, value_a DOUBLE, value_b DOUBLE, PRIMARY KEY (id));

CREATE NODE TABLE ProjectItem (id INT64, name STRING, email STRING, phone STRING, address STRING, city STRING, country STRING, zipcode STRING, bio STRING, status STRING, role STRING, tier STRING, level STRING, badge STRING, category STRING, tag STRING, label STRING, score DOUBLE, rating DOUBLE, balance DOUBLE, income DOUBLE, price DOUBLE, discount DOUBLE, tax DOUBLE, weight DOUBLE, age INT64, count INT64, views INT64, likes INT64, shares INT64, followers INT64, friends INT64, posts INT64, flag_a BOOL, flag_b BOOL, flag_c BOOL, flag_d BOOL, flag_e BOOL, flag_f BOOL, flag_g BOOL, flag_h BOOL, flag_i BOOL, metric_a DOUBLE, metric_b DOUBLE, metric_c DOUBLE, metric_d DOUBLE, desc_a STRING, desc_b STRING, desc_c STRING, desc_d STRING, created_at STRING, updated_at STRING, deleted_at STRING, published_at STRING, extra_a STRING, extra_b STRING, extra_c STRING, extra_d STRING, value_a DOUBLE, value_b DOUBLE, PRIMARY KEY (id));

CREATE NODE TABLE ReviewItem (id INT64, name STRING, email STRING, phone STRING, address STRING, city STRING, country STRING, zipcode STRING, bio STRING, status STRING, role STRING, tier STRING, level STRING, badge STRING, category STRING, tag STRING, label STRING, score DOUBLE, rating DOUBLE, balance DOUBLE, income DOUBLE, price DOUBLE, discount DOUBLE, tax DOUBLE, weight DOUBLE, age INT64, count INT64, views INT64, likes INT64, shares INT64, followers INT64, friends INT64, posts INT64, flag_a BOOL, flag_b BOOL, flag_c BOOL, flag_d BOOL, flag_e BOOL, flag_f BOOL, flag_g BOOL, flag_h BOOL, flag_i BOOL, metric_a DOUBLE, metric_b DOUBLE, metric_c DOUBLE, metric_d DOUBLE, desc_a STRING, desc_b STRING, desc_c STRING, desc_d STRING, created_at STRING, updated_at STRING, deleted_at STRING, published_at STRING, extra_a STRING, extra_b STRING, extra_c STRING, extra_d STRING, value_a DOUBLE, value_b DOUBLE, PRIMARY KEY (id));

CREATE NODE TABLE PhotoItem (id INT64, name STRING, email STRING, phone STRING, address STRING, city STRING, country STRING, zipcode STRING, bio STRING, status STRING, role STRING, tier STRING, level STRING, badge STRING, category STRING, tag STRING, label STRING, score DOUBLE, rating DOUBLE, balance DOUBLE, income DOUBLE, price DOUBLE, discount DOUBLE, tax DOUBLE, weight DOUBLE, age INT64, count INT64, views INT64, likes INT64, shares INT64, followers INT64, friends INT64, posts INT64, flag_a BOOL, flag_b BOOL, flag_c BOOL, flag_d BOOL, flag_e BOOL, flag_f BOOL, flag_g BOOL, flag_h BOOL, flag_i BOOL, metric_a DOUBLE, metric_b DOUBLE, metric_c DOUBLE, metric_d DOUBLE, desc_a STRING, desc_b STRING, desc_c STRING, desc_d STRING, created_at STRING, updated_at STRING, deleted_at STRING, published_at STRING, extra_a STRING, extra_b STRING, extra_c STRING, extra_d STRING, value_a DOUBLE, value_b DOUBLE, PRIMARY KEY (id));

CREATE NODE TABLE ArticleItem (id INT64, name STRING, email STRING, phone STRING, address STRING, city STRING, country STRING, zipcode STRING, bio STRING, status STRING, role STRING, tier STRING, level STRING, badge STRING, category STRING, tag STRING, label STRING, score DOUBLE, rating DOUBLE, balance DOUBLE, income DOUBLE, price DOUBLE, discount DOUBLE, tax DOUBLE, weight DOUBLE, age INT64, count INT64, views INT64, likes INT64, shares INT64, followers INT64, friends INT64, posts INT64, flag_a BOOL, flag_b BOOL, flag_c BOOL, flag_d BOOL, flag_e BOOL, flag_f BOOL, flag_g BOOL, flag_h BOOL, flag_i BOOL, metric_a DOUBLE, metric_b DOUBLE, metric_c DOUBLE, metric_d DOUBLE, desc_a STRING, desc_b STRING, desc_c STRING, desc_d STRING, created_at STRING, updated_at STRING, deleted_at STRING, published_at STRING, extra_a STRING, extra_b STRING, extra_c STRING, extra_d STRING, value_a DOUBLE, value_b DOUBLE, PRIMARY KEY (id));

CREATE NODE TABLE CourseItem (id INT64, name STRING, email STRING, phone STRING, address STRING, city STRING, country STRING, zipcode STRING, bio STRING, status STRING, role STRING, tier STRING, level STRING, badge STRING, category STRING, tag STRING, label STRING, score DOUBLE, rating DOUBLE, balance DOUBLE, income DOUBLE, price DOUBLE, discount DOUBLE, tax DOUBLE, weight DOUBLE, age INT64, count INT64, views INT64, likes INT64, shares INT64, followers INT64, friends INT64, posts INT64, flag_a BOOL, flag_b BOOL, flag_c BOOL, flag_d BOOL, flag_e BOOL, flag_f BOOL, flag_g BOOL, flag_h BOOL, flag_i BOOL, metric_a DOUBLE, metric_b DOUBLE, metric_c DOUBLE, metric_d DOUBLE, desc_a STRING, desc_b STRING, desc_c STRING, desc_d STRING, created_at STRING, updated_at STRING, deleted_at STRING, published_at STRING, extra_a STRING, extra_b STRING, extra_c STRING, extra_d STRING, value_a DOUBLE, value_b DOUBLE, PRIMARY KEY (id));

CREATE NODE TABLE CertificateItem (id INT64, name STRING, email STRING, phone STRING, address STRING, city STRING, country STRING, zipcode STRING, bio STRING, status STRING, role STRING, tier STRING, level STRING, badge STRING, category STRING, tag STRING, label STRING, score DOUBLE, rating DOUBLE, balance DOUBLE, income DOUBLE, price DOUBLE, discount DOUBLE, tax DOUBLE, weight DOUBLE, age INT64, count INT64, views INT64, likes INT64, shares INT64, followers INT64, friends INT64, posts INT64, flag_a BOOL, flag_b BOOL, flag_c BOOL, flag_d BOOL, flag_e BOOL, flag_f BOOL, flag_g BOOL, flag_h BOOL, flag_i BOOL, metric_a DOUBLE, metric_b DOUBLE, metric_c DOUBLE, metric_d DOUBLE, desc_a STRING, desc_b STRING, desc_c STRING, desc_d STRING, created_at STRING, updated_at STRING, deleted_at STRING, published_at STRING, extra_a STRING, extra_b STRING, extra_c STRING, extra_d STRING, value_a DOUBLE, value_b DOUBLE, PRIMARY KEY (id));

// ---- Edge Tables ----
CREATE REL TABLE AccountWritesComment (FROM Account TO CommentItem, since INT64, weight DOUBLE, label STRING);

CREATE REL TABLE AccountWorksAtCompany (FROM Account TO Company, since INT64, weight DOUBLE, label STRING);

CREATE REL TABLE OrderContainsProduct (FROM OrderItem TO Product, since INT64, weight DOUBLE, label STRING);

CREATE REL TABLE AccountWritesReview (FROM Account TO ReviewItem, since INT64, weight DOUBLE, label STRING);

CREATE REL TABLE ProductHasReview (FROM Product TO ReviewItem, since INT64, weight DOUBLE, label STRING);

CREATE REL TABLE ProjectHasTask (FROM ProjectItem TO TaskItem, since INT64, weight DOUBLE, label STRING);

CREATE REL TABLE AccountCreatesPost (FROM Account TO PostItem, since INT64, weight DOUBLE, label STRING);

CREATE REL TABLE AccountJoinsGroup (FROM Account TO GroupItem, since INT64, weight DOUBLE, label STRING);

CREATE REL TABLE AccountPlacesOrder (FROM Account TO OrderItem, since INT64, weight DOUBLE, label STRING);

CREATE REL TABLE AccountEarnsCert (FROM Account TO CertificateItem, since INT64, weight DOUBLE, label STRING);

CREATE REL TABLE AccountAttendsEvent (FROM Account TO EventItem, since INT64, weight DOUBLE, label STRING);

CREATE REL TABLE AccountEnrollsCourse (FROM Account TO CourseItem, since INT64, weight DOUBLE, label STRING);

CREATE REL TABLE PostHasTag (FROM PostItem TO Tag, since INT64, weight DOUBLE, label STRING);

CREATE REL TABLE PostInCategory (FROM PostItem TO Category, since INT64, weight DOUBLE, label STRING);

CREATE REL TABLE ProductInCategory (FROM Product TO Category, since INT64, weight DOUBLE, label STRING);

CREATE REL TABLE CompanyHasDept (FROM Company TO Department, since INT64, weight DOUBLE, label STRING);

CREATE REL TABLE EventAtLocation (FROM EventItem TO LocationItem, since INT64, weight DOUBLE, label STRING);
